
import { PlanItem } from './types';

type PlanData = {
    [key: string]: PlanItem[];
};

export const planData_VinhGoc: PlanData = {
    '3': [
        { tuan: 1, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 1: Thông tin và quyết định', tiet: 1, nls: [], ghiChu: '' },
        { tuan: 2, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 2: Xử lý thông tin', tiet: 2, nls: [], ghiChu: '' },
        { tuan: 3, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 3: Máy tính - Những người bạn mới', tiet: 3, nls: [], ghiChu: '' },
        { tuan: 4, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 4: Làm việc với máy tính', tiet: 4, nls: [], ghiChu: '' },
        { tuan: 5, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 5: Sử dụng bàn phím', tiet: 5, nls: [], ghiChu: '' },
        { tuan: 6, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 5: Sử dụng bàn phím (Tiếp)', tiet: 6, nls: [], ghiChu: '' },
        { tuan: 7, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 6: Chuột máy tính', tiet: 7, nls: [], ghiChu: '' },
        { tuan: 8, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 7: Làm quen với internet', tiet: 8, nls: [], ghiChu: '' },
        { tuan: 9, chuDe: 'Chủ đề B. Mạng máy tính và Internet', tenBaiHoc: 'Bài 8: An toàn và hợp pháp khi sử dụng internet', tiet: 9, nls: [], ghiChu: '' },
        { tuan: 10, chuDe: 'Chủ đề C. Tổ chức lưu trữ, tìm kiếm', tenBaiHoc: 'Bài 9: Lưu trữ thông tin trong máy tính', tiet: 10, nls: [], ghiChu: '' },
        { tuan: 11, chuDe: 'Chủ đề C. Tổ chức lưu trữ, tìm kiếm', tenBaiHoc: 'Bài 10: Sắp xếp và tìm kiếm', tiet: 11, nls: [], ghiChu: '' },
        { tuan: 12, chuDe: 'Chủ đề D. Đạo đức, pháp luật và văn hóa', tenBaiHoc: 'Bài 11: Ứng xử trên môi trường số', tiet: 12, nls: [], ghiChu: '' },
        { tuan: 13, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 12: Làm quen với phần mềm trình chiếu', tiet: 13, nls: [], ghiChu: '' },
        { tuan: 14, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 12: Làm quen với phần mềm trình chiếu (Tiếp)', tiet: 14, nls: [], ghiChu: '' },
        { tuan: 15, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 13: Thực hành trình chiếu', tiet: 15, nls: [], ghiChu: '' },
        { tuan: 16, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 13: Thực hành trình chiếu (Tiếp)', tiet: 16, nls: [], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì 1', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra học kì 1', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 14: Làm quen với phần mềm luyện gõ phím', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 14: Làm quen với phần mềm luyện gõ phím (Tiếp)', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 15: Luyện gõ phím', tiet: 21, nls: [], ghiChu: '' },
        { tuan: 22, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 16: Các bước thực hiện công việc', tiet: 22, nls: [], ghiChu: '' },
        { tuan: 23, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 16: Các bước thực hiện công việc (Tiếp)', tiet: 23, nls: [], ghiChu: '' },
        { tuan: 24, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 17: Làm quen với cấu trúc tuần tự', tiet: 24, nls: [], ghiChu: '' },
        { tuan: 25, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 17: Làm quen với cấu trúc tuần tự (Tiếp)', tiet: 25, nls: [], ghiChu: '' },
        { tuan: 26, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 18: Nhiệm vụ của em và sự trợ giúp của máy tính', tiet: 26, nls: [], ghiChu: '' },
        { tuan: 27, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 18: Nhiệm vụ của em và sự trợ giúp của máy tính (Tiếp)', tiet: 27, nls: [], ghiChu: '' },
        { tuan: 28, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 19: Thực hiện công việc theo các bước', tiet: 28, nls: [], ghiChu: '' },
        { tuan: 29, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 19: Thực hiện công việc theo các bước (Tiếp)', tiet: 29, nls: [], ghiChu: '' },
        { tuan: 30, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 20: Chia nhỏ công việc', tiet: 30, nls: [], ghiChu: '' },
        { tuan: 31, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 20: Chia nhỏ công việc (Tiếp)', tiet: 31, nls: [], ghiChu: '' },
        { tuan: 32, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 21: Luyện tập tổng hợp', tiet: 32, nls: [], ghiChu: '' },
        { tuan: 33, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 21: Luyện tập tổng hợp (Tiếp)', tiet: 33, nls: [], ghiChu: '' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì 2', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra học kì 2', tiet: 35, nls: [], ghiChu: '' },
    ],
    '4': [
        { tuan: 1, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 1. Phần cứng và phần mềm máy tính', tiet: 1, nls: [], ghiChu: '' },
        { tuan: 2, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 2. Một số thao tác gây lỗi, hỏng cho phần cứng, phần mềm', tiet: 2, nls: [], ghiChu: '' },
        { tuan: 3, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 3. Gõ phím với hàng phím số', tiet: 3, nls: [], ghiChu: '' },
        { tuan: 4, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 4. Lợi ích của việc gõ bàn phím đúng cách', tiet: 4, nls: [], ghiChu: '' },
        { tuan: 5, chuDe: 'Chủ đề 2: Mạng máy tính và Internet', tenBaiHoc: 'Bài 5. Thông tin trên trang web', tiet: 5, nls: [], ghiChu: '' },
        { tuan: 6, chuDe: 'Chủ đề 2: Mạng máy tính và Internet', tenBaiHoc: 'Bài 6. Tác hại khi xem những trang web không phù hợp', tiet: 6, nls: [], ghiChu: '' },
        { tuan: 7, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 7. Tìm thông tin trên internet theo từ khoá', tiet: 7, nls: [], ghiChu: '' },
        { tuan: 8, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 8. Tìm kiếm hình ảnh trên internet', tiet: 8, nls: [], ghiChu: '' },
        { tuan: 9, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 9. Thực hành tìm kiếm thông tin trên internet', tiet: 9, nls: [], ghiChu: '' },
        { tuan: 10, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 10. Các thao tác với tệp và thư mục', tiet: 10, nls: [], ghiChu: '' },
        { tuan: 11, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 11. Thực hành thao tác với tệp, thư mục', tiet: 11, nls: [], ghiChu: '' },
        { tuan: 12, chuDe: 'Chủ đề 4. Đạo đức, pháp luật', tenBaiHoc: 'Bài 12. Phần mềm miễn phí và không miễn phí', tiet: 12, nls: [], ghiChu: '' },
        { tuan: 13, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 13. Phần mềm soạn thảo văn bản', tiet: 13, nls: [], ghiChu: '' },
        { tuan: 14, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 14. Soạn thảo văn bản', tiet: 14, nls: [], ghiChu: '' },
        { tuan: 15, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 15. Chèn hình ảnh vào văn bản', tiet: 15, nls: [], ghiChu: '' },
        { tuan: 16, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 16. Sao chép, di chuyển, xóa văn bản', tiet: 16, nls: [], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 17. Thực hành soạn thảo văn bản', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 18. Tạo bài trình chiếu', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 19. Dấu đầu dòng trong trang chiếu', tiet: 21, nls: [], ghiChu: '' },
        { tuan: 22, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 20. Định dạng văn bản trong trang chiếu', tiet: 22, nls: [], ghiChu: '' },
        { tuan: 23, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 21. Tạo hiệu ứng chuyển trang', tiet: 23, nls: [], ghiChu: '' },
        { tuan: 24, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 22. Thực hành tạo bài trình chiếu', tiet: 24, nls: [], ghiChu: '' },
        { tuan: 25, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 23. Sử dụng phần mềm luyện tập gõ bàn phím', tiet: 25, nls: [], ghiChu: '' },
        { tuan: 26, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 24. Làm quen với phần mềm scratch', tiet: 26, nls: [], ghiChu: '' },
        { tuan: 27, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 25. Nhóm lệnh và lệnh', tiet: 27, nls: [], ghiChu: '' },
        { tuan: 28, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 26. Chương trình scratch', tiet: 28, nls: [], ghiChu: '' },
        { tuan: 29, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 27. Tạo, xoá nhân vật, thay đổi phông nền', tiet: 29, nls: [], ghiChu: '' },
        { tuan: 30, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 28. Nhóm lệnh bút vẽ', tiet: 30, nls: [], ghiChu: '' },
        { tuan: 31, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 29. Nhân bản khối lệnh', tiet: 31, nls: [], ghiChu: '' },
        { tuan: 32, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 30. Lệnh ẩn, hiện lệnh đợi', tiet: 32, nls: [], ghiChu: '' },
        { tuan: 33, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 31. Tạo chương trình cho nhiều nhân vật', tiet: 33, nls: [], ghiChu: '' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ],
    '5': [
        { tuan: 1, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 1. Máy tính giúp em học tập', tiet: 1, nls: [], ghiChu: '' },
        { tuan: 2, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 2. Máy tính giúp em giải trí', tiet: 2, nls: [], ghiChu: '' },
        { tuan: 3, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 3. Máy tính giúp em tìm kiếm, trao đổi thông tin', tiet: 3, nls: [], ghiChu: '' },
        { tuan: 4, chuDe: 'Chương 2. Mạng máy tính', tenBaiHoc: 'Bài 4. Tìm kiếm thông tin trên website', tiet: 4, nls: [], ghiChu: '' },
        { tuan: 5, chuDe: 'Chương 2. Mạng máy tính', tenBaiHoc: 'Bài 5. Thực hành tìm kiếm thông tin trên website', tiet: 5, nls: [], ghiChu: '' },
        { tuan: 6, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 6. Tìm thông tin trong giải quyết vấn đề', tiet: 6, nls: [], ghiChu: '' },
        { tuan: 7, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 7. Cấu trúc cây thư mục hợp lý', tiet: 7, nls: [], ghiChu: '' },
        { tuan: 8, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 8. Tìm tệp, thư mục trên máy tính', tiet: 8, nls: [], ghiChu: '' },
        { tuan: 9, chuDe: 'Chương 4. Đạo đức, pháp luật', tenBaiHoc: 'Bài 9. Bản quyền nội dung thông tin', tiet: 9, nls: [], ghiChu: '' },
        { tuan: 10, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 10. Chọn và xóa khối văn bản', tiet: 10, nls: [], ghiChu: '' },
        { tuan: 11, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 11. Sao chép, di chuyển khối văn bản', tiet: 11, nls: [], ghiChu: '' },
        { tuan: 12, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 12. Định dạng ký tự', tiet: 12, nls: [], ghiChu: '' },
        { tuan: 13, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 13. Thực hành định dạng văn bản', tiet: 13, nls: [], ghiChu: '' },
        { tuan: 14, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 14. Chèn hình ảnh vào văn bản', tiet: 14, nls: [], ghiChu: '' },
        { tuan: 15, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 15. Thực hành chèn ảnh vào văn bản', tiet: 15, nls: [], ghiChu: '' },
        { tuan: 16, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 16A. Sử dụng phần mềm đồ họa', tiet: 16, nls: [], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Ôn tập học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 17. Cấu trúc tuần tự', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 18. Thực hành về cấu trúc tuần tự', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 19. Cấu trúc lặp với số lần biết trước', tiet: 21, nls: [], ghiChu: '' },
        { tuan: 22, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 20. Thực hành về cấu trúc lặp', tiet: 22, nls: [], ghiChu: '' },
        { tuan: 23, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 21. Cấu trúc lặp liên tục', tiet: 23, nls: [], ghiChu: '' },
        { tuan: 24, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 22. Thực hành về cấu trúc lặp liên tục', tiet: 24, nls: [], ghiChu: '' },
        { tuan: 25, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 23. Cấu trúc lặp có điều kiện', tiet: 25, nls: [], ghiChu: '' },
        { tuan: 26, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 24. Thực hành về lặp với cấu trúc có điều kiện', tiet: 26, nls: [], ghiChu: '' },
        { tuan: 27, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 25. Biến nhớ', tiet: 27, nls: [], ghiChu: '' },
        { tuan: 28, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 26. Biểu thức', tiet: 28, nls: [], ghiChu: '' },
        { tuan: 29, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 27. Thực hành về biến nhớ và biểu thức', tiet: 29, nls: [], ghiChu: '' },
        { tuan: 30, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 28. Cấu trúc rẽ nhánh dạng thiếu', tiet: 30, nls: [], ghiChu: '' },
        { tuan: 31, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 29. Cấu trúc rẽ nhánh dạng đủ', tiet: 31, nls: [], ghiChu: '' },
        { tuan: 32, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 30. Thực hành về cấu trúc rẽ nhánh', tiet: 32, nls: [], ghiChu: '' },
        { tuan: 33, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 31. Kịch bản chương trình và chạy thử', tiet: 33, nls: [], ghiChu: '' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ]
};

export const planData_CV3456_Mapped: PlanData = {
    '3': [
        { tuan: 1, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 1: Thông tin và quyết định', tiet: 1, nls: ['1.1.CB1a'], ghiChu: 'LT' },
        { tuan: 2, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 2: Xử lý thông tin', tiet: 2, nls: ['1.1.CB1c'], ghiChu: 'LT' },
        { tuan: 3, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 3: Máy tính - Những người bạn mới', tiet: 3, nls: ['1.1.CB1c'], ghiChu: 'LT' },
        { tuan: 4, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 4: Làm việc với máy tính', tiet: 4, nls: ['4.1.CB1a'], ghiChu: 'LT' },
        { tuan: 5, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 5: Sử dụng bàn phím', tiet: 5, nls: ['4.1.CB1a'], ghiChu: 'LT' },
        { tuan: 6, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 5: Sử dụng bàn phím (Tiếp)', tiet: 6, nls: ['4.1.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 7, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 6: Chuột máy tính', tiet: 7, nls: ['4.1.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 8, chuDe: 'Chủ đề A. Máy tính và em', tenBaiHoc: 'Bài 7: Làm quen với internet', tiet: 8, nls: ['1.1.CB1a', '1.1.CB1b'], ghiChu: 'LT' },
        { tuan: 9, chuDe: 'Chủ đề B. Mạng máy tính và Internet', tenBaiHoc: 'Bài 8: An toàn và hợp pháp khi sử dụng internet', tiet: 9, nls: ['4.2.CB1a', '2.5.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 10, chuDe: 'Chủ đề C. Tổ chức lưu trữ, tìm kiếm', tenBaiHoc: 'Bài 9: Lưu trữ thông tin trong máy tính', tiet: 10, nls: ['1.3.CB1a'], ghiChu: 'LT' },
        { tuan: 11, chuDe: 'Chủ đề C. Tổ chức lưu trữ, tìm kiếm', tenBaiHoc: 'Bài 10: Sắp xếp và tìm kiếm', tiet: 11, nls: ['1.3.CB1b'], ghiChu: 'LT' },
        { tuan: 12, chuDe: 'Chủ đề D. Đạo đức, pháp luật và văn hóa', tenBaiHoc: 'Bài 11: Ứng xử trên môi trường số', tiet: 12, nls: ['2.5.CB1a', '2.5.CB1b'], ghiChu: 'LT + TH' },
        { tuan: 13, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 12: Làm quen với phần mềm trình chiếu', tiet: 13, nls: ['3.1.CB1a'], ghiChu: 'TH' },
        { tuan: 14, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 12: Làm quen với phần mềm trình chiếu (Tiếp)', tiet: 14, nls: ['3.1.CB1a'], ghiChu: 'TH' },
        { tuan: 15, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 13: Thực hành trình chiếu', tiet: 15, nls: ['3.1.CB1b'], ghiChu: 'TH' },
        { tuan: 16, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 13: Thực hành trình chiếu (Tiếp)', tiet: 16, nls: ['3.1.CB1b'], ghiChu: 'LT + TH' },
        { tuan: 17, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì 1', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra học kì 1', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 14: Làm quen với phần mềm luyện gõ phím', tiet: 19, nls: ['3.1.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 20, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 14: Làm quen với phần mềm luyện gõ phím (Tiếp)', tiet: 20, nls: ['3.1.CB1a'], ghiChu: 'LT' },
        { tuan: 21, chuDe: 'Chủ đề E. Ứng dụng tin học', tenBaiHoc: 'Bài 15: Luyện gõ phím', tiet: 21, nls: ['3.1.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 22, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 16: Các bước thực hiện công việc', tiet: 22, nls: ['5.1.CB1a'], ghiChu: 'LT + TH' },
        { tuan: 23, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 16: Các bước thực hiện công việc (Tiếp)', tiet: 23, nls: ['5.1.CB1b'], ghiChu: 'LT + TH' },
        { tuan: 24, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 17: Làm quen với cấu trúc tuần tự', tiet: 24, nls: ['3.4.CB1a'], ghiChu: 'TH' },
        { tuan: 25, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 17: Làm quen với cấu trúc tuần tự (Tiếp)', tiet: 25, nls: ['3.4.CB1a'], ghiChu: 'TH' },
        { tuan: 26, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 18: Nhiệm vụ của em và sự trợ giúp của máy tính', tiet: 26, nls: ['3.4.CB1a'], ghiChu: 'LT' },
        { tuan: 27, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 18: Nhiệm vụ của em và sự trợ giúp của máy tính (Tiếp)', tiet: 27, nls: ['3.4.CB1a'], ghiChu: 'LT' },
        { tuan: 28, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 19: Thực hiện công việc theo các bước', tiet: 28, nls: ['5.1.CB1a', '5.1.CB1b'], ghiChu: 'LT' },
        { tuan: 29, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 19: Thực hiện công việc theo các bước (Tiếp)', tiet: 29, nls: ['5.1.CB1a', '5.1.CB1b'], ghiChu: 'LT' },
        { tuan: 30, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 20: Chia nhỏ công việc', tiet: 30, nls: ['5.1.CB1b'], ghiChu: 'LT' },
        { tuan: 31, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 20: Chia nhỏ công việc (Tiếp)', tiet: 31, nls: ['5.1.CB1b'], ghiChu: 'LT' },
        { tuan: 32, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 21: Luyện tập tổng hợp', tiet: 32, nls: ['3.4.CB1a', '5.1.CB1b'], ghiChu: 'TH' },
        { tuan: 33, chuDe: 'Chủ đề F. Giải quyết vấn đề', tenBaiHoc: 'Bài 21: Luyện tập tổng hợp (Tiếp)', tiet: 33, nls: ['3.4.CB1a', '5.1.CB1b'], ghiChu: 'TH' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì 2', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra học kì 2', tiet: 35, nls: [], ghiChu: '' },
    ],
    '4': [
        { tuan: 1, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 1. Phần cứng và phần mềm máy tính', tiet: 1, nls: ['1.1.CB2a', '1.1.CB2c'], ghiChu: '' },
        { tuan: 2, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 2. Một số thao tác gây lỗi, hỏng cho phần cứng, phần mềm', tiet: 2, nls: ['5.1.CB2a', '5.1.CB2b'], ghiChu: '' },
        { tuan: 3, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 3. Gõ phím với hàng phím số', tiet: 3, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 4, chuDe: 'Chủ đề 1: Máy tính và em', tenBaiHoc: 'Bài 4. Lợi ích của việc gõ bàn phím đúng cách', tiet: 4, nls: ['4.3.CB2a'], ghiChu: '' },
        { tuan: 5, chuDe: 'Chủ đề 2: Mạng máy tính và Internet', tenBaiHoc: 'Bài 5. Thông tin trên trang web', tiet: 5, nls: ['1.1.CB2b', '1.1.CB2c'], ghiChu: '' },
        { tuan: 6, chuDe: 'Chủ đề 2: Mạng máy tính và Internet', tenBaiHoc: 'Bài 6. Tác hại khi xem những trang web không phù hợp', tiet: 6, nls: ['4.3.CB2b', '4.2.CB2a'], ghiChu: '' },
        { tuan: 7, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 7. Tìm thông tin trên internet theo từ khoá', tiet: 7, nls: ['1.1.CB2b', '1.1.CB2d'], ghiChu: '' },
        { tuan: 8, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 8. Tìm kiếm hình ảnh trên internet', tiet: 8, nls: ['1.1.CB2b'], ghiChu: '' },
        { tuan: 9, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 9. Thực hành tìm kiếm thông tin trên internet', tiet: 9, nls: ['1.1.CB2b', '1.1.CB2d'], ghiChu: '' },
        { tuan: 10, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 10. Các thao tác với tệp và thư mục', tiet: 10, nls: ['1.3.CB2a'], ghiChu: '' },
        { tuan: 11, chuDe: 'Chủ đề 3: Tổ chức lưu trữ', tenBaiHoc: 'Bài 11. Thực hành thao tác với tệp, thư mục', tiet: 11, nls: ['1.3.CB2a', '1.3.CB2b'], ghiChu: '' },
        { tuan: 12, chuDe: 'Chủ đề 4. Đạo đức, pháp luật', tenBaiHoc: 'Bài 12. Phần mềm miễn phí và không miễn phí', tiet: 12, nls: ['3.3.CB2a'], ghiChu: '' },
        { tuan: 13, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 13. Phần mềm soạn thảo văn bản', tiet: 13, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 14, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 14. Soạn thảo văn bản', tiet: 14, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 15, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 15. Chèn hình ảnh vào văn bản', tiet: 15, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 16, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 16. Sao chép, di chuyển, xóa văn bản', tiet: 16, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 17. Thực hành soạn thảo văn bản', tiet: 19, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 20, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 18. Tạo bài trình chiếu', tiet: 20, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 21, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 19. Dấu đầu dòng trong trang chiếu', tiet: 21, nls: ['3.1.CB2a', '3.1.CB2b'], ghiChu: '' },
        { tuan: 22, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 20. Định dạng văn bản trong trang chiếu', tiet: 22, nls: ['3.1.CB2a', '3.1.CB2b'], ghiChu: '' },
        { tuan: 23, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 21. Tạo hiệu ứng chuyển trang', tiet: 23, nls: ['3.1.CB2a', '3.1.CB2b'], ghiChu: '' },
        { tuan: 24, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 22. Thực hành tạo bài trình chiếu', tiet: 24, nls: ['3.1.CB2a', '3.1.CB2b'], ghiChu: '' },
        { tuan: 25, chuDe: 'Chủ đề 5. Ứng dụng tin học', tenBaiHoc: 'Bài 23. Sử dụng phần mềm luyện tập gõ bàn phím', tiet: 25, nls: ['3.1.CB2a'], ghiChu: 'Chủ đề con tự chọn' },
        { tuan: 26, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 24. Làm quen với phần mềm scratch', tiet: 26, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 27, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 25. Nhóm lệnh và lệnh', tiet: 27, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 28, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 26. Chương trình scratch', tiet: 28, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 29, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 27. Tạo, xoá nhân vật, thay đổi phông nền', tiet: 29, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 30, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 28. Nhóm lệnh bút vẽ', tiet: 30, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 31, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 29. Nhân bản khối lệnh', tiet: 31, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 32, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 30. Lệnh ẩn, hiện lệnh đợi', tiet: 32, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 33, chuDe: 'Chủ đề 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 31. Tạo chương trình cho nhiều nhân vật', tiet: 33, nls: ['3.4.CB2a'], ghiChu: '' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ],
    '5': [
        { tuan: 1, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 1. Máy tính giúp em học tập', tiet: 1, nls: ['1.1.CB2c', '5.2.CB2b'], ghiChu: 'LT-TH' },
        { tuan: 2, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 2. Máy tính giúp em giải trí', tiet: 2, nls: ['1.1.CB2c', '5.2.CB2b'], ghiChu: 'LT-TH' },
        { tuan: 3, chuDe: 'Chương 1. Máy tính và em', tenBaiHoc: 'Bài 3. Máy tính giúp em tìm kiếm, trao đổi thông tin', tiet: 3, nls: ['1.1.CB2b', '2.1.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 4, chuDe: 'Chương 2. Mạng máy tính', tenBaiHoc: 'Bài 4. Tìm kiếm thông tin trên website', tiet: 4, nls: ['1.1.CB2b', '1.2.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 5, chuDe: 'Chương 2. Mạng máy tính', tenBaiHoc: 'Bài 5. Thực hành tìm kiếm thông tin trên website', tiet: 5, nls: ['1.1.CB2b', '2.4.CB2a'], ghiChu: 'TH' },
        { tuan: 6, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 6. Tìm thông tin trong giải quyết vấn đề', tiet: 6, nls: ['1.1.CB2a', '5.2.CB2b'], ghiChu: 'LT- TH' },
        { tuan: 7, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 7. Cấu trúc cây thư mục hợp lý', tiet: 7, nls: ['1.3.CB2b'], ghiChu: 'LT-TH' },
        { tuan: 8, chuDe: 'Chương 3. Tổ chức lưu trữ', tenBaiHoc: 'Bài 8. Tìm tệp, thư mục trên máy tính', tiet: 8, nls: ['1.3.CB2a'], ghiChu: 'TH' },
        { tuan: 9, chuDe: 'Chương 4. Đạo đức, pháp luật', tenBaiHoc: 'Bài 9. Bản quyền nội dung thông tin', tiet: 9, nls: ['3.3.CB2a', '2.5.CB2c'], ghiChu: 'LT' },
        { tuan: 10, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 10. Chọn và xóa khối văn bản', tiet: 10, nls: ['3.1.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 11, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 11. Sao chép, di chuyển khối văn bản', tiet: 11, nls: ['3.1.CB2a'], ghiChu: 'TH' },
        { tuan: 12, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 12. Định dạng ký tự', tiet: 12, nls: ['3.1.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 13, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 13. Thực hành định dạng văn bản', tiet: 13, nls: ['3.1.CB2a'], ghiChu: 'TH' },
        { tuan: 14, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 14. Chèn hình ảnh vào văn bản', tiet: 14, nls: ['3.1.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 15, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 15. Thực hành chèn ảnh vào văn bản', tiet: 15, nls: ['3.1.CB2a'], ghiChu: 'TH' },
        { tuan: 16, chuDe: 'Chương 5. Ứng dụng tin học', tenBaiHoc: 'Bài 16A. Sử dụng phần mềm đồ họa', tiet: 16, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 17, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Ôn tập học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 17. Cấu trúc tuần tự', tiet: 19, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 20, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 18. Thực hành về cấu trúc tuần tự', tiet: 20, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 21, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 19. Cấu trúc lặp với số lần biết trước', tiet: 21, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 22, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 20. Thực hành về cấu trúc lặp', tiet: 22, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 23, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 21. Cấu trúc lặp liên tục', tiet: 23, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 24, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 22. Thực hành về cấu trúc lặp liên tục', tiet: 24, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 25, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 23. Cấu trúc lặp có điều kiện', tiet: 25, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 26, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 24. Thực hành về lặp với cấu trúc có điều kiện', tiet: 26, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 27, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 25. Biến nhớ', tiet: 27, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 28, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 26. Biểu thức', tiet: 28, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 29, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 27. Thực hành về biến nhớ và biểu thức', tiet: 29, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 30, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 28. Cấu trúc rẽ nhánh dạng thiếu', tiet: 30, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 31, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 29. Cấu trúc rẽ nhánh dạng đủ', tiet: 31, nls: ['3.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 32, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 30. Thực hành về cấu trúc rẽ nhánh', tiet: 32, nls: ['3.4.CB2a', '5.3.CB2b'], ghiChu: 'TH' },
        { tuan: 33, chuDe: 'Chương 6. Giải quyết vấn đề', tenBaiHoc: 'Bài 31. Kịch bản chương trình và chạy thử', tiet: 33, nls: ['3.4.CB2a', '5.3.CB2b', '2.4.CB2a'], ghiChu: 'LT-TH' },
        { tuan: 34, chuDe: 'Ôn tập', tenBaiHoc: 'Ôn tập kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ]
};

export const planData_CongNghe_Raw: PlanData = {
    '3': [],
    '4': [
        { tuan: 1, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (1 tiết)', tiet: 1, nls: [], ghiChu: '' },
        { tuan: 2, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (2 tiết)', tiet: 2, nls: [], ghiChu: '' },
        { tuan: 3, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (3 tiết)', tiet: 3, nls: [], ghiChu: '' },
        { tuan: 4, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 1)', tiet: 4, nls: [], ghiChu: '' },
        { tuan: 5, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 2)', tiet: 5, nls: [], ghiChu: '' },
        { tuan: 6, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 3)', tiet: 6, nls: [], ghiChu: '' },
        { tuan: 7, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (T1)', tiet: 7, nls: [], ghiChu: 'KNS BÀI 9: Biết một số loại hoa, cây cảnh phổ biến để có ý thức bảo vệ và chăm sóc cây xanh.' },
        { tuan: 8, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (tiết 2)', tiet: 8, nls: [], ghiChu: '' },
        { tuan: 9, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (tiết 3)', tiet: 9, nls: [], ghiChu: '' },
        { tuan: 10, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 1)', tiet: 10, nls: [], ghiChu: 'KNS BÀI 9: Biết chăm sóc hoa, cây cảnh trong chậu để làm đẹp môi trường. Sử dụng phân bón, thuốc trừ sâu hợp lí để bảo vệ môi trường.' },
        { tuan: 11, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 2)', tiet: 11, nls: [], ghiChu: 'KNS BÀI 9: Biết gieo hạt hoa, cây cảnh trong chậu để làm đẹp môi trường.' },
        { tuan: 12, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 3)', tiet: 12, nls: [], ghiChu: '' },
        { tuan: 13, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 1)', tiet: 13, nls: [], ghiChu: 'Thay thế bài học stem : Chậu cây thân thiện với môi trường' },
        { tuan: 14, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 2)', tiet: 14, nls: [], ghiChu: '' },
        { tuan: 15, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 3)', tiet: 15, nls: [], ghiChu: '' },
        { tuan: 16, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 1)', tiet: 16, nls: [], ghiChu: 'KNS BÀI 9: Biết trồng hoa, cây cảnh trong chậu để làm đẹp môi trường.' },
        { tuan: 17, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Ôn tập cuối HK1', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Kiểm tra cuối HK1', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 2)', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 3)', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 7: Giới thiệu bộ lắp ghép mô hình kĩ thuật (tiết 1)', tiet: 21, nls: [], ghiChu: '' },
        { tuan: 22, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 7: Giới thiệu bộ lắp ghép mô hình kĩ thuật (tiết 2)', tiet: 22, nls: [], ghiChu: '' },
        { tuan: 23, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 8: Lắp ghép mô hình bập bênh (tiết 1)', tiet: 23, nls: [], ghiChu: '' },
        { tuan: 24, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 8: Lắp ghép mô hình bập bênh (tiết 2)', tiet: 24, nls: [], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 25, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 1)', tiet: 25, nls: [], ghiChu: '' },
        { tuan: 26, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 2)', tiet: 26, nls: [], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 27, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 3)', tiet: 27, nls: [], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 28, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 10: Đồ chơi dân gian (tiết 1)', tiet: 28, nls: [], ghiChu: '' },
        { tuan: 29, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 10: Đồ chơi dân gian (tiết 2)', tiet: 29, nls: [], ghiChu: 'Dạy hoạt động trải nghiệm stem: Đèn lồng trung thu' },
        { tuan: 30, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 11: Làm đèn lồng (tiết 1)', tiet: 30, nls: [], ghiChu: '' },
        { tuan: 31, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 11: Làm đèn lồng (tiết 2)', tiet: 31, nls: [], ghiChu: '' },
        { tuan: 32, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 12: Làm chuồn chuồn thăng bằng (tiết 1)', tiet: 32, nls: [], ghiChu: '' },
        { tuan: 33, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 12: Làm chuồn chuồn thăng bằng (tiết 2)', tiet: 33, nls: [], ghiChu: '' },
        { tuan: 34, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Ôn tập cuối HK2', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Kiểm tra cuối HK2', tiet: 35, nls: [], ghiChu: '' },
    ],
    '5': [
        { tuan: 1, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 1: Vai trò của công nghệ (Tiết 1)', tiet: 1, nls: [], ghiChu: '' },
        { tuan: 2, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 1: Vai trò của công nghệ (Tiết 2)', tiet: 2, nls: [], ghiChu: '' },
        { tuan: 3, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 1)', tiet: 3, nls: [], ghiChu: '' },
        { tuan: 4, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 2)', tiet: 4, nls: [], ghiChu: '' },
        { tuan: 5, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 3)', tiet: 5, nls: [], ghiChu: '' },
        { tuan: 6, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 4)', tiet: 6, nls: [], ghiChu: '' },
        { tuan: 7, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 3: Tìm hiểu thiết kế (Tiết 1)', tiet: 7, nls: [], ghiChu: '' },
        { tuan: 8, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 3: Tìm hiểu thiết kế (Tiết 2)', tiet: 8, nls: [], ghiChu: '' },
        { tuan: 9, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 1)', tiet: 9, nls: [], ghiChu: '' },
        { tuan: 10, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 2)', tiet: 10, nls: [], ghiChu: '' },
        { tuan: 11, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 3)', tiet: 11, nls: [], ghiChu: '' },
        { tuan: 12, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 4)', tiet: 12, nls: [], ghiChu: '' },
        { tuan: 13, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 1)', tiet: 13, nls: [], ghiChu: '' },
        { tuan: 14, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 2)', tiet: 14, nls: [], ghiChu: '' },
        { tuan: 15, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 3)', tiet: 15, nls: [], ghiChu: 'Giáo dục kĩ năng PCCC và CNCH: Chủ đề 4: Hậu quả khi xảy ra cháy (Học sinh biết cách sử dụng điện thoại an toàn)' },
        { tuan: 16, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 4)', tiet: 16, nls: [], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Ôn tập cuối học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 1)', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 2)', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 3)', tiet: 21, nls: [], ghiChu: '' },
        { tuan: 22, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 1)', tiet: 22, nls: [], ghiChu: '' },
        { tuan: 23, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 2)', tiet: 23, nls: [], ghiChu: '' },
        { tuan: 24, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 3)', tiet: 24, nls: [], ghiChu: '' },
        { tuan: 25, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 4)', tiet: 25, nls: [], ghiChu: '' },
        { tuan: 26, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 1)', tiet: 26, nls: [], ghiChu: '' },
        { tuan: 27, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 2)', tiet: 27, nls: [], ghiChu: '' },
        { tuan: 28, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 3)', tiet: 28, nls: [], ghiChu: 'STEM' },
        { tuan: 29, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 4)', tiet: 29, nls: [], ghiChu: '' },
        { tuan: 30, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 1)', tiet: 30, nls: [], ghiChu: '' },
        { tuan: 31, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 2)', tiet: 31, nls: [], ghiChu: '' },
        { tuan: 32, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 3)', tiet: 32, nls: [], ghiChu: '' },
        { tuan: 33, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 4)', tiet: 33, nls: [], ghiChu: '' },
        { tuan: 34, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Ôn tập cuối học kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ]
};

export const planData_CongNghe_Mapped: PlanData = {
    '3': [
        { tuan: 1, chuDe: 'Tự nhiên và công nghệ', tenBaiHoc: 'Bài 1. Tự nhiên và công nghệ (T1)', tiet: 1, nls: ['1.1.CB1a'], ghiChu: '' },
        { tuan: 2, chuDe: 'Tự nhiên và công nghệ', tenBaiHoc: 'Bài 1. Tự nhiên và công nghệ (T2)', tiet: 2, nls: ['1.1.CB1a'], ghiChu: '' },
        { tuan: 3, chuDe: 'Sử dụng đèn học', tenBaiHoc: 'Bài 2. Sử dụng đèn học (T1)', tiet: 3, nls: ['4.1.CB1a'], ghiChu: '' },
        { tuan: 4, chuDe: 'Sử dụng đèn học', tenBaiHoc: 'Bài 2. Sử dụng đèn học (T2)', tiet: 4, nls: ['4.1.CB1a'], ghiChu: '' },
        { tuan: 5, chuDe: 'Sử dụng quạt điện', tenBaiHoc: 'Bài 3. Sử dụng quạt điện (T1)', tiet: 5, nls: ['4.1.CB1a'], ghiChu: '' },
        { tuan: 6, chuDe: 'Sử dụng quạt điện', tenBaiHoc: 'Bài 3. Sử dụng quạt điện (T2)', tiet: 6, nls: ['4.1.CB1a'], ghiChu: '' },
        { tuan: 7, chuDe: 'Sử dụng máy thu thanh', tenBaiHoc: 'Bài 4. Sử dụng máy thu thanh (T1)', tiet: 7, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 8, chuDe: 'Sử dụng máy thu thanh', tenBaiHoc: 'Bài 4. Sử dụng máy thu thanh (T2)', tiet: 8, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 9, chuDe: 'Sử dụng máy thu thanh', tenBaiHoc: 'Bài 4. Sử dụng máy thu thanh (T3)', tiet: 9, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 10, chuDe: 'Sử dụng máy thu thanh', tenBaiHoc: 'Bài 4. Sử dụng máy thu thanh (T4)', tiet: 10, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 11, chuDe: 'Sử dụng máy thu hình', tenBaiHoc: 'Bài 5. Sử dụng máy thu hình (T1)', tiet: 11, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 12, chuDe: 'Sử dụng máy thu hình', tenBaiHoc: 'Bài 5. Sử dụng máy thu hình (T2)', tiet: 12, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 13, chuDe: 'Sử dụng máy thu hình', tenBaiHoc: 'Bài 5. Sử dụng máy thu hình (T3)', tiet: 13, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 14, chuDe: 'Sử dụng máy thu hình', tenBaiHoc: 'Bài 5. Sử dụng máy thu hình (T4)', tiet: 14, nls: ['2.1.CB1b'], ghiChu: '' },
        { tuan: 15, chuDe: 'An toàn với môi trường công nghệ trong gia đình', tenBaiHoc: 'Bài 6. An toàn với môi trường công nghệ trong gia đình (T1)', tiet: 15, nls: ['4.1.CB1c'], ghiChu: '' },
        { tuan: 16, chuDe: 'An toàn với môi trường công nghệ trong gia đình', tenBaiHoc: 'Bài 6. An toàn với môi trường công nghệ trong gia đình (T2)', tiet: 16, nls: ['4.1.CB1c'], ghiChu: '' },
        { tuan: 17, chuDe: 'An toàn với môi trường công nghệ trong gia đình', tenBaiHoc: 'Bài 6. An toàn với môi trường công nghệ trong gia đình (T3)', tiet: 17, nls: ['4.1.CB1c'], ghiChu: '' },
        { tuan: 18, chuDe: 'An toàn với môi trường công nghệ trong gia đình', tenBaiHoc: 'Bài 6. An toàn với môi trường công nghệ trong gia đình (T4)', tiet: 18, nls: ['4.1.CB1c'], ghiChu: '' },
        { tuan: 19, chuDe: 'Ôn tập kiểm tra', tenBaiHoc: 'Ôn tập kiểm tra học kì I (T1)', tiet: 19, nls: [], ghiChu: '' },
        { tuan: 20, chuDe: 'Ôn tập kiểm tra', tenBaiHoc: 'Ôn tập kiểm tra học kì I (T2)', tiet: 20, nls: [], ghiChu: '' },
        { tuan: 21, chuDe: 'Làm đồ dùng học tập', tenBaiHoc: 'Bài 7. Dụng cụ và vật liệu làm thủ công (T1)', tiet: 21, nls: ['5.2.CB1b'], ghiChu: '' },
        { tuan: 22, chuDe: 'Làm đồ dùng học tập', tenBaiHoc: 'Bài 7. Dụng cụ và vật liệu làm thủ công (T2)', tiet: 22, nls: ['5.2.CB1b'], ghiChu: '' },
        { tuan: 23, chuDe: 'Làm đồ dùng học tập', tenBaiHoc: 'Bài 8. Làm đồ dùng học tập (T1)', tiet: 23, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 24, chuDe: 'Làm đồ dùng học tập', tenBaiHoc: 'Bài 8. Làm đồ dùng học tập (T2)', tiet: 24, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 25, chuDe: 'Làm đồ dùng học tập', tenBaiHoc: 'Bài 8. Làm đồ dùng học tập (T3)', tiet: 25, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 26, chuDe: 'Làm biển báo giao thông', tenBaiHoc: 'Bài 9. Làm biển báo giao thông (T1)', tiet: 26, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 27, chuDe: 'Làm biển báo giao thông', tenBaiHoc: 'Bài 9. Làm biển báo giao thông (T2)', tiet: 27, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 28, chuDe: 'Làm biển báo giao thông', tenBaiHoc: 'Bài 9. Làm biển báo giao thông (T3)', tiet: 28, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 29, chuDe: 'Làm biển báo giao thông', tenBaiHoc: 'Bài 9. Làm biển báo giao thông (T4)', tiet: 29, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 30, chuDe: 'Làm đồ chơi', tenBaiHoc: 'Bài 10. Làm đồ chơi (T1)', tiet: 30, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 31, chuDe: 'Làm đồ chơi', tenBaiHoc: 'Bài 10. Làm đồ chơi (T2)', tiet: 31, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 32, chuDe: 'Làm đồ chơi', tenBaiHoc: 'Bài 10. Làm đồ chơi (T3)', tiet: 32, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 33, chuDe: 'Làm đồ chơi', tenBaiHoc: 'Bài 10. Làm đồ chơi (T4)', tiet: 33, nls: ['5.3.CB1a'], ghiChu: '' },
        { tuan: 34, chuDe: 'Ôn tập kiểm tra', tenBaiHoc: 'Ôn tập kiểm tra học kì II (T1)', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Ôn tập kiểm tra', tenBaiHoc: 'Ôn tập kiểm tra học kì II (T2)', tiet: 35, nls: [], ghiChu: '' },
    ],
    '4': [
        { tuan: 1, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (1 tiết)', tiet: 1, nls: ['1.1.CB2b', '4.4.CB2a'], ghiChu: '' },
        { tuan: 2, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (2 tiết)', tiet: 2, nls: ['1.1.CB2b', '4.4.CB2a'], ghiChu: '' },
        { tuan: 3, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 1: Lợi ích của hoa, cây cảnh đối với đời sống. (3 tiết)', tiet: 3, nls: ['1.1.CB2b', '4.4.CB2a'], ghiChu: '' },
        { tuan: 4, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 1)', tiet: 4, nls: ['1.1.CB2a'], ghiChu: '' },
        { tuan: 5, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 2)', tiet: 5, nls: ['1.1.CB2a'], ghiChu: '' },
        { tuan: 6, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 2: Một số loại hoa, cây cảnh phổ biến (tiết 3)', tiet: 6, nls: ['1.1.CB2a'], ghiChu: '' },
        { tuan: 7, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (T1)', tiet: 7, nls: ['1.3.CB2a'], ghiChu: 'KNS BÀI 9: Biết một số loại hoa, cây cảnh phổ biến để có ý thức bảo vệ và chăm sóc cây xanh.' },
        { tuan: 8, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (tiết 2)', tiet: 8, nls: ['1.3.CB2a'], ghiChu: '' },
        { tuan: 9, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 3: Vật liệu và dụng cụ trồng hoa, cây cảnh trong chậu (tiết 3)', tiet: 9, nls: ['1.3.CB2a'], ghiChu: '' },
        { tuan: 10, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 1)', tiet: 10, nls: ['3.1.CB2a', '4.4.CB2a'], ghiChu: 'KNS BÀI 9: Biết chăm sóc hoa, cây cảnh trong chậu để làm đẹp môi trường. Sử dụng phân bón, thuốc trừ sâu hợp lí để bảo vệ môi trường.' },
        { tuan: 11, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 2)', tiet: 11, nls: ['3.1.CB2a', '4.4.CB2a'], ghiChu: 'KNS BÀI 9: Biết gieo hạt hoa, cây cảnh trong chậu để làm đẹp môi trường.' },
        { tuan: 12, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 4: Gieo hạt hoa, cây cảnh trong chậu (tiết 3)', tiet: 12, nls: ['3.1.CB2a'], ghiChu: '' },
        { tuan: 13, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 1)', tiet: 13, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: 'Thay thế bài học stem : Chậu cây thân thiện với môi trường' },
        { tuan: 14, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 2)', tiet: 14, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 15, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 5: Trồng hoa, cây cảnh trong chậu (tiết 3)', tiet: 15, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 16, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 1)', tiet: 16, nls: ['4.4.CB2a'], ghiChu: 'KNS BÀI 9: Biết trồng hoa, cây cảnh trong chậu để làm đẹp môi trường.' },
        { tuan: 17, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Ôn tập cuối HK1', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Kiểm tra cuối HK1', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 2)', tiet: 19, nls: ['4.4.CB2a'], ghiChu: '' },
        { tuan: 20, chuDe: 'Phần 1: Công nghệ và đời sống', tenBaiHoc: 'Bài 6: Chăm sóc hoa, cây cảnh trong chậu (tiết 3)', tiet: 20, nls: ['4.4.CB2a'], ghiChu: '' },
        { tuan: 21, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 7: Giới thiệu bộ lắp ghép mô hình kĩ thuật (tiết 1)', tiet: 21, nls: ['1.1.CB2a', '5.1.CB2a'], ghiChu: '' },
        { tuan: 22, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 7: Giới thiệu bộ lắp ghép mô hình kĩ thuật (tiết 2)', tiet: 22, nls: ['1.1.CB2a', '5.1.CB2a'], ghiChu: '' },
        { tuan: 23, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 8: Lắp ghép mô hình bập bênh (tiết 1)', tiet: 23, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 24, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 8: Lắp ghép mô hình bập bênh (tiết 2)', tiet: 24, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 25, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 1)', tiet: 25, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 26, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 2)', tiet: 26, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 27, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 9: Lắp ghép mô hình robot (tiết 3)', tiet: 27, nls: ['5.2.CB2b', '5.3.CB2a'], ghiChu: 'KNS BÀI 7: Vận dụng tư duy sáng tạo để lắp ghép mô hình.' },
        { tuan: 28, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 10: Đồ chơi dân gian (tiết 1)', tiet: 28, nls: ['3.1.CB2b'], ghiChu: '' },
        { tuan: 29, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 10: Đồ chơi dân gian (tiết 2)', tiet: 29, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: 'Dạy hoạt động trải nghiệm stem: Đèn lồng trung thu' },
        { tuan: 30, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 11: Làm đèn lồng (tiết 1)', tiet: 30, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 31, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 11: Làm đèn lồng (tiết 2)', tiet: 31, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 32, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 12: Làm chuồn chuồn thăng bằng (tiết 1)', tiet: 32, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 33, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Bài 12: Làm chuồn chuồn thăng bằng (tiết 2)', tiet: 33, nls: ['3.1.CB2b', '5.3.CB2a'], ghiChu: '' },
        { tuan: 34, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Ôn tập cuối HK2', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'Phần 2: Thủ công kĩ thuật', tenBaiHoc: 'Kiểm tra cuối HK2', tiet: 35, nls: [], ghiChu: '' },
    ],
    '5': [
        { tuan: 1, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 1: Vai trò của công nghệ (Tiết 1)', tiet: 1, nls: ['1.1.CB2b'], ghiChu: '' },
        { tuan: 2, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 1: Vai trò của công nghệ (Tiết 2)', tiet: 2, nls: ['1.1.CB2b'], ghiChu: '' },
        { tuan: 3, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 1)', tiet: 3, nls: ['1.2.CB2a', '3.3.CB2a'], ghiChu: '' },
        { tuan: 4, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 2)', tiet: 4, nls: ['1.2.CB2a', '3.3.CB2a'], ghiChu: '' },
        { tuan: 5, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 3)', tiet: 5, nls: ['1.2.CB2a', '3.3.CB2a'], ghiChu: '' },
        { tuan: 6, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 2: Nhà sáng chế (Tiết 4)', tiet: 6, nls: ['1.2.CB2a', '3.3.CB2a'], ghiChu: '' },
        { tuan: 7, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 3: Tìm hiểu thiết kế (Tiết 1)', tiet: 7, nls: ['3.1.CB2a', '5.2.CB2a'], ghiChu: '' },
        { tuan: 8, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 3: Tìm hiểu thiết kế (Tiết 2)', tiet: 8, nls: ['3.1.CB2a', '5.2.CB2a'], ghiChu: '' },
        { tuan: 9, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 1)', tiet: 9, nls: ['3.1.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 10, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 2)', tiet: 10, nls: ['3.1.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 11, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 3)', tiet: 11, nls: ['3.1.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 12, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 4: Thiết kế sản phẩm (Tiết 4)', tiet: 12, nls: ['3.1.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 13, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 1)', tiet: 13, nls: ['4.1.CB2a', '2.5.CB2a'], ghiChu: '' },
        { tuan: 14, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 2)', tiet: 14, nls: ['4.1.CB2a', '2.5.CB2a'], ghiChu: '' },
        { tuan: 15, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 3)', tiet: 15, nls: ['4.1.CB2a', '2.5.CB2a', '4.3.CB2a'], ghiChu: 'Giáo dục kĩ năng PCCC và CNCH: Chủ đề 4: Hậu quả khi xảy ra cháy (Học sinh biết cách sử dụng điện thoại an toàn)' },
        { tuan: 16, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 5: Sử dụng điện thoại (Tiết 4)', tiet: 16, nls: ['4.1.CB2a', '2.5.CB2a'], ghiChu: '' },
        { tuan: 17, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Ôn tập cuối học kì I', tiet: 17, nls: [], ghiChu: '' },
        { tuan: 18, chuDe: 'Ôn tập và kiểm tra', tenBaiHoc: 'Kiểm tra định kỳ cuối kì I', tiet: 18, nls: [], ghiChu: '' },
        { tuan: 19, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 1)', tiet: 19, nls: ['1.1.CB2a', '4.4.CB2a'], ghiChu: '' },
        { tuan: 20, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 2)', tiet: 20, nls: ['1.1.CB2a', '4.4.CB2a'], ghiChu: '' },
        { tuan: 21, chuDe: 'PHẦN MỘT. CÔNG NGHỆ VÀ ĐỜI SỐNG', tenBaiHoc: 'Bài 6: Sử dụng tủ lạnh (Tiết 3)', tiet: 21, nls: ['1.1.CB2a', '4.4.CB2a'], ghiChu: '' },
        { tuan: 22, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 1)', tiet: 22, nls: ['5.1.CB2a', '5.2.CB2b'], ghiChu: '' },
        { tuan: 23, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 2)', tiet: 23, nls: ['5.1.CB2a', '5.2.CB2b'], ghiChu: '' },
        { tuan: 24, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 3)', tiet: 24, nls: ['5.1.CB2a', '5.2.CB2b'], ghiChu: '' },
        { tuan: 25, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 7: Lắp ráp mô hình xe điện chạy bằng pin (tiết 4)', tiet: 25, nls: ['5.1.CB2a', '5.2.CB2b'], ghiChu: '' },
        { tuan: 26, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 1)', tiet: 26, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 27, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 2)', tiet: 27, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 28, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 3)', tiet: 28, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: 'STEM' },
        { tuan: 29, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 8: Mô hình máy phát điện gió (Tiết 4)', tiet: 29, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 30, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 1)', tiet: 30, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 31, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 2)', tiet: 31, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 32, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 3)', tiet: 32, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 33, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Bài 9: Mô hình điện mặt trời (Tiết 4)', tiet: 33, nls: ['4.4.CB2a', '5.3.CB2a'], ghiChu: '' },
        { tuan: 34, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Ôn tập cuối học kì II', tiet: 34, nls: [], ghiChu: '' },
        { tuan: 35, chuDe: 'PHẦN II: THỦ CÔNG KĨ THUẬT', tenBaiHoc: 'Kiểm tra định kỳ cuối năm học', tiet: 35, nls: [], ghiChu: '' },
    ]
};

export const csvDataL123 = `
BẢNG MÔ TẢ MỨC ĐỘ NĂNG LỰC SỐ CỦA HỌC SINH LỚP 1-2-3,,
,,
L1-L2-L3 (Cơ bản 1),,
Miền NL 1,1. Khai thác dữ liệu và thông tin,Tin học
NL thành phần 1,"1.1. Duyệt, tìm kiếm và lọc dữ liệu, thông tin và nội dung số.",
,"Xác định được nhu cầu thông tin; tìm kiếm được dữ liệu, thông tin và nội dung trong môi trường số; truy cập chúng và khai thác được kết quả tìm kiếm. Tạo và cập nhật được chiến lược tìm kiếm.",
1.1.CB1a,"a- Xác định nhu cầu thông tin, tìm kiếm và truy cập nội dung đơn giản trong môi trường số, xác định chiến lược tìm kiếm đơn giản.",
1.1.CB1b,"b- Tìm được cách truy cập những dữ liệu, thông tin và nội dung này cũng như điều hướng giữa chúng,",
1.1.CB1c,c- Xác định được các chiến lược tìm kiếm đơn giản,
NL thành phần 2,"1.2. Đánh giá dữ liệu, thông tin và nội dung số",
,"Phân tích, so sánh và đánh giá được độ tin cậy và tính xác thực của nguồn dữ liệu, thông tin và nội dung số. Phân tích, giải thích và đánh giá được dữ liệu, thông tin và nội dung số.",
1.2.CB1a,"a. Phát hiện được độ tin cậy và độ chính xác của các nguồn chung của dữ liệu, thông tin và nội dung số.",
NL thành phần 3,"1.3. Quản lý dữ liệu, thông tin và nội dung số",
,"Tổ chức, lưu trữ và truy xuất được dữ liệu, thông tin và nội dung trong môi trường số. Tổ chức và sắp xếp được chúng trong một môi trường có cấu trúc.",
1.3.CB1a,"a. Xác định được cách tổ chức, lưu trữ và truy xuất dữ liệu, thông tin và nội dung một cách đơn giản trong môi trường số.",
1.3.CB1b,"b. Nhận biết được nơi để sắp xếp dữ liệu, thông tin và nội dung một cách đơn giản trong môi trường có cấu trúc.",
Miền NL 2,2. Giao tiếp và Hợp tác,Tin học
NL thành phần 1,"2.1. Tương tác thông qua công nghệ số",
,"Tương tác thông qua các công nghệ số khác nhau và nhận biết được phương tiện giao tiếp số nào phù hợp cho một bối cảnh nhất định.",
2.1.CB1a,"a. Lựa chọn được các công nghệ số đơn giản để tương tác.",
2.1.CB1b,"b. Xác định được các phương tiện giao tiếp đơn giản thích hợp cho một bối cảnh cụ thể.",
NL thành phần 2,"2.2. Chia sẻ thông tin và nội dung thông qua công nghệ số",
,"Chia sẻ dữ liệu, thông tin và nội dung số với người khác thông qua các công nghệ số phù hợp. Đóng vai trò là người trung gian, hiểu biết và thực hành trích dẫn và ghi chú nguồn.",
2.2.CB1a,"a. Nhận biết được các công nghệ số đơn giản, phù hợp để chia sẻ dữ liệu, thông tin và nội dung kỹ thuật số.",
2.2.CB1b,"b. Nhận biết được phương pháp trích dẫn và ghi nguồn cơ bản.",
NL thành phần 3,"2.3. Sử dụng công nghệ số để thực hiện trách nhiệm công dân",
,"Tham gia vào xã hội thông qua việc sử dụng các dịch vụ số công cộng và tư nhân. Tìm kiếm được cơ hội, để trao quyền và thu hút công dân thông qua các công nghệ số phù hợp.",
2.3.CB1a,"a. Xác định được các dịch vụ số đơn giản để có thể tham gia vào xã hội.",
2.3.CB1b,"b. Nhận biết được các công nghệ số đơn giản, phù hợp để nâng cao năng lực cho bản thân và tham gia vào xã hội với tư cách là một công dân.",
NL thành phần 4,"2.4. Hợp tác thông qua công nghệ số",
,"Sử dụng được các công cụ và công nghệ số cho các quá trình hợp tác cũng như để cùng xây dựng và đồng sáng tạo dữ liệu, tài nguyên và kiến thức.",
2.4.CB1a,"a. Chọn được những công cụ và công nghệ số đơn giản cho các quá trình cộng tác.",
NL thành phần 5,"2.5. Quy tắc ứng xử trên mạng",
,"Nhận thức được các chuẩn mực hành vi và kiến thức khi sử dụng công nghệ số và tương tác trong môi trường số. Điều chỉnh các chiến lược giao tiếp phù hợp với đối tượng cụ thể và nhận thức đa dạng về văn hóa và thế hệ trong môi trường số.",
2.5.CB1a,"a. Phân biệt được các chuẩn mực hành vi đơn giản và biết cách sử dụng công nghệ số và tương tác trong môi trường số.",
2.5.CB1b,"b. Chọn được các phương thức và chiến lược giao tiếp đơn giản phù hợp trong môi trường số.",
2.5.CB1c,"c. Phân biệt các khía cạnh đơn giản của sự đa dạng về văn hóa và thế hệ cần được tính đến trong môi trường số.",
NL thành phần 6,"2.6. Quản lý danh tính số",
,"Tạo và quản lý được một hoặc nhiều danh tính số để bảo vệ danh tiếng của bản thân, làm việc với dữ liệu mà một người tạo ra bằng nhiều công cụ môi trường và dịch vụ số.",
2.6.CB1a,"a. Xác định được danh tính số.",
2.6.CB1b,"b. Mô tả được những cách đơn giản để bảo vệ danh tiếng trực tuyến của bản thân.",
2.6.CB1c,"c. Nhận biết được dữ liệu đơn giản do mình tạo ra thông qua các công cụ, môi trường hoặc dịch vụ số.",
Miền NL 3,3. Sáng tạo nội dung số,Tin học
NL thành phần 1,"3.1 Phát triển nội dung số",
,"Tạo và chỉnh sửa được nội dung số ở các định dạng khác nhau, nhằm thể hiện bản thân thông qua các phương tiện số.",
3.1.CB1a,"a. Xác định được các cách tạo và chỉnh sửa nội dung đơn giản ở các định dạng đơn giản,",
3.1.CB1b,"b. Chọn được cách thể hiện bản thân thông qua việc tạo ra các nội dung số đơn giản.",
NL thành phần 2,"3.2. Tích hợp và tạo lập lại nội dung số",
,"Sửa đổi, tinh chỉnh và tích hợp được thông tin và nội dung mới vào khối kiến thức và tài nguyên hiện có để tạo ra nội dung và kiến thức mới, độc đáo và phù hợp.",
3.2.CB1a,"a. Chọn được các cách sửa đổi, tinh chỉnh, cải thiện và tích hợp các mục đơn giản có nội dung và thông tin mới để tạo ra những nội dung và thông tin mới và độc đáo.",
NL thành phần 3,"3.3. Thực thi bản quyền và giấy phép",
,"Hiểu được cách áp dụng bản quyền và giấy phép cho thông tin và nội dung số",
3.3.CB1a,"a. Xác định được các quy tắc đơn giản về bản quyền và giấy phép áp dụng cho dữ liệu, thông tin và nội dung số.",
NL thành phần 4,3.4 Lập trình,
,"Lập được kế hoạch và phát triển được một chuỗi các câu lệnh dễ hiểu cho một hệ thống máy tính để giải quyết một vấn đề nhất định hoặc thực hiện một nhiệm vụ cụ thể",
3.4.CB1a,"a. Liệt kê được các hướng dẫn đơn giản để hệ thống máy tính giải quyết một vấn đề đơn giản hoặc thực hiện một nhiệm vụ đơn giản.",
Miền NL 4,4. An toàn,Tin học
NL thành phần 1,"4.1. Bảo vệ thiết bị",
,"Bảo vệ được thiết bị và nội dung số; hiểu được rõ rủi ro và mối đe dọa trong môi trường số; nắm được các biện pháp an toàn và bảo mật; quan tâm đến mức độ tin cậy và quyền riêng tư.",
4.1.CB1a,"a. Nhận biết được cách bảo vệ thiết bị và nội dung số một cách đơn giản.",
4.1.CB1b,"b. Phân biệt được rủi ro và mối đe dọa đơn giản trong môi trường số.",
4.1.CB1c,"c. Chọn lựa được các biện pháp an toàn và bảo mật đơn giản.",
4.1.CB1d,"d. Nhận biết được những cách thức đơn giản để quan tâm đến mức độ tin cậy và quyền riêng tư.",
NL thành phần 2,"4.2 Bảo vệ dữ liệu cá nhân và quyền riêng tư",
,"Bảo vệ được dữ liệu cá nhân và quyền riêng tư trong môi trường số. Hiểu được cách sử dụng và chia sẻ thông tin định danh cá nhân một cách an toàn có khả năng bảo vệ bản thân và người khác. Hiểu được cách các dịch vụ số sử dụng “Chính sách Quyền riêng tư” để thông báo phương thức sử dụng dữ liệu cá nhân.",
4.2.CB1a,"a. Lựa chọn được những cách thức đơn giản để bảo vệ dữ liệu cá nhân và quyền riêng tư trong môi trường số.",
4.2.CB1b,"b. Nhận biết được các cách sử dụng và chia sẻ thông tin định danh cá nhân một cách an toàn, có khả năng bảo vệ bản thân và người khác.",
4.2.CB1c,"c. Nhận diện được các tuyên bố cơ bản trong chính sách quyền riêng tư về cách sử dụng dữ liệu cá nhân trong dịch vụ số.",
NL thành phần 3,"4.3 Bảo vệ sức khỏe và an sinh số",
,"Tránh được rủi ro và đe dọa đến sức khỏe thể chất và tinh thần khi sử dụng công nghệ số. Bảo vệ được bản thân và người khác khỏi nguy cơ trong môi trường số (ví dụ: bắt nạt trên mạng). Nhận biết được những công nghệ số cho tăng cường thịnh vượng xã hội và sự hòa hợp trong xã hội.",
4.3.CB1a,"a. Phân biệt được các cách thức đơn giản để tránh rủi ro và đe dọa đến sức khỏe thể chất và tinh thần khi sử dụng công nghệ số.",
4.3.CB1b,"b. Lựa chọn được những cách thức đơn giản để bảo vệ bản thân khỏi nguy cơ trong môi trường số.",
4.3.CB1c,"c. Nhận biết được những công nghệ số đơn giản cho tăng cường thịnh vượng xã hội và sự hòa hợp trong xã hội.",
NL thành phần 4,"4.4 Bảo vệ môi trường",
,"Nhận thức được tác động của công nghệ số và việc sử dụng công nghệ số đối với môi trường.",
4.4.CB1a,"a. Nhận biết được tác động cơ bản của công nghệ số và việc sử dụng công nghệ số đối với môi trường.",
Miền NL 5,5. Giải quyết vấn đề,Tin học
NL thành phần 1,"5.1. Giải quyết các vấn đề kỹ thuật",
,"Xác định được các vấn đề kỹ thuật khi vận hành thiết bị, sử dụng môi trường số và giải quyết chúng (từ xử lý sự cố đến giải quyết các vấn đề phức tạp hơn).",
5.1.CB1a,"a. Xác định được các vấn đề kỹ thuật đơn giản khi vận hành thiết bị và sử dụng môi trường số.",
5.1.CB1b,"b. Xác định được các giải pháp đơn giản để giải quyết chúng.",
NL thành phần 2,"5.2 Xác định nhu cầu và giải pháp công nghệ",
,"Đánh giá được nhu cầu và xác định, đánh giá, lựa chọn, sử dụng các công cụ số cùng với các giải pháp công nghệ khả thi để giải quyết chúng. Điều chỉnh và tùy chỉnh được môi trường số theo nhu cầu cá nhân (ví dụ: khả năng tiếp cận).",
5.2.CB1a,"a. Xác định được nhu cầu cá nhân.",
5.2.CB1b,"b. Nhận ra được các công cụ số đơn giản và các giải pháp công nghệ có thể có để giải quyết những nhu cầu đó.",
5.2.CB1c,"c. Chọn được những cách đơn giản để điều chỉnh và tùy chỉnh môi trường số theo nhu cầu cá nhân.",
NL thành phần 3,"5.3 Sử dụng sáng tạo công nghệ số",
,"Sử dụng các công cụ và công nghệ số để tạo ra kiến thức, đổi mới quy trình và sản phẩm. Gắn kết cá nhân và tập thể vào quá trình xử lý nhận thức để hiểu và giải quyết các vấn đề mang tính khái niệm và các tình huống có vấn đề trong môi trường số.",
5.3.CB1a,"a. Xác định được các công cụ và công nghệ số đơn giản có thể được sử dụng để tạo ra kiến thức và đổi mới quy trình cũng như sản phẩm.",
5.3.CB1b,"b. Thể hiện được sự quan tâm của cá nhân và tập thể đến quá trình xử lý nhận thức đơn giản để hiểu và giải quyết các vấn đề khái niệm đơn giản và các tình huống có vấn đề trong môi trường số.",
NL thành phần 4,"5.4 Xác định các vấn đề cần cải thiện về NLS",
,"Hiểu được NLS của chính mình cần được cải thiện hoặc cập nhật ở đâu. Có thể hỗ trợ người khác phát triển NLS của họ. Tìm kiếm được cơ hội phát triển bản thân và cập nhật sự phát triển số.",
5.4.CB1a,a. Nhận ra được NLS của tôi cần được cải thiện hoặc cập nhật ở đâu.,
5.4.CB1b,b. Xác định được nơi để tìm kiếm cơ hội phát triển bản thân và cập nhật sự phát triển công nghệ số.,
Miền NL 6,6. Ứng dụng trí tuệ nhân tạo,
NL thành phần 1,6.1 Hiểu biết về trí tuệ nhân tạo,
,"Sử dụng hiệu quả các hệ thống AI và hiểu rõ ứng dụng thực tế của chúng. Sử dụng được AI để tạo nội dung, khám phá kiến thức và giải quyết các vấn đề trong công việc và cuộc sống hàng ngày.",
,,
NL thành phần 2,6.2 Sử dụng trí tuệ nhân tạo,
,"Đánh giá và lọc được thông tin từ các nguồn được tạo ra hoặc xử lý bằng AI, để hiểu rõ hơn về tính đáng tin cậy và cách sử dụng thông tin đó. Đánh giá được AI trên các khía cạnh minh bạch, an toàn, đạo đức và tác động.",
6.2.CB1a,a. Nhận diện được các công cụ AI đơn giản.,
6.2.CB1b,b. Thực hiện được các thao tác cơ bản với các công cụ AI.,
6.2.CB1c,c. Nhận thức được cơ bản về các vấn đề đạo đức và pháp lý liên quan đến AI.,
NL thành phần 3,6.3 Đánh giá trí tuệ nhân tạo,
,"Đánh giá và lọc được thông tin từ các nguồn được tạo ra hoặc xử lý bằng AI, để hiểu rõ hơn về tính đáng tin cậy và cách sử dụng thông tin đó. Đánh giá được AI trên các khía cạnh minh bạch, an toàn, đạo đức và tác động.",
6.3.CB1a,"a. Nhận diện được một số vật dụng/trò chơi thông minh có sử dụng AI",
6.3.CB1b,"b. Nhớ được rằng không phải mọi thông tin từ máy móc đều đúng",
`;

export const csvDataL45 = `
BẢNG MÔ TẢ MỨC ĐỘ NĂNG LỰC SỐ CỦA HỌC SINH LỚP 4-5,,
,,
L4-L5 (Cơ bản 2),,
Miền NL 1,1. Khai thác dữ liệu và thông tin,Tin học
NL thành phần 1,"1.1. Duyệt, tìm kiếm và lọc dữ liệu, thông tin và nội dung số.",
,"Xác định được nhu cầu thông tin; tìm kiếm được dữ liệu, thông tin và nội dung trong môi trường số; truy cập chúng và khai thác được kết quả tìm kiếm. Tạo và cập nhật được chiến lược tìm kiếm.",
1.1.CB2a,a. Xác định được nhu cầu thông tin.,
1.1.CB2b,"b. Tìm được dữ liệu, thông tin và nội dung thông qua tìm kiếm đơn giản trong môi trường số.",
1.1.CB2c,"c. Tìm được cách truy cập những dữ liệu, thông tin và nội dung này cũng như điều hướng giữa chúng.",
1.1.CB2d,d. Xác định được các chiến lược tìm kiếm đơn giản.,
NL thành phần 2,"1.2. Đánh giá dữ liệu, thông tin và nội dung số",
,"Phân tích, so sánh và đánh giá được độ tin cậy và tính xác thực của nguồn dữ liệu, thông tin và nội dung số. Phân tích, giải thích và đánh giá được dữ liệu, thông tin và nội dung số.",
1.2.CB2a,"a. Phát hiện được độ tin cậy và độ chính xác của các nguồn chung của dữ liệu, thông tin và nội dung số.",
NL thành phần 3,"1.3. Quản lý dữ liệu, thông tin và nội dung số",
,"Tổ chức, lưu trữ và truy xuất được dữ liệu, thông tin và nội dung trong môi trường số. Tổ chức và sắp xếp được chúng trong một môi trường có cấu trúc.",
1.3.CB2a,"a. Xác định được cách tổ chức, lưu trữ và truy xuất dữ liệu, thông tin và nội dung một cách đơn giản trong môi trường số.",
1.3.CB2b,"b. Nhận biết được nơi để sắp xếp dữ liệu, thông tin và nội dung một cách đơn giản trong môi trường có cấu trúc.",
Miền NL 2,2. Giao tiếp và Hợp tác,Tin học
NL thành phần 1,"2.1. Tương tác thông qua công nghệ số",
,"Tương tác thông qua các công nghệ số khác nhau và nhận biết được phương tiện giao tiếp số nào phù hợp cho một bối cảnh nhất định.",
2.1.CB2a,"a. Lựa chọn được các công nghệ số đơn giản để tương tác.",
2.1.CB2b,"b. Xác định được các phương tiện giao tiếp đơn giản thích hợp cho một bối cảnh cụ thể.",
NL thành phần 2,"2.2. Chia sẻ thông tin và nội dung thông qua công nghệ số",
,"Chia sẻ dữ liệu, thông tin và nội dung số với người khác thông qua các công nghệ số phù hợp. Đóng vai trò là người trung gian, hiểu biết và thực hành trích dẫn và ghi chú nguồn.",
2.2.CB2a,"a. Nhận biết được các công nghệ số đơn giản, phù hợp để chia sẻ dữ liệu, thông tin và nội dung kỹ thuật số.",
2.2.CB2b,"b. Xác định được phương pháp trích dẫn và ghi nguồn cơ bản.",
NL thành phần 3,"2.3. Sử dụng công nghệ số để thực hiện trách nhiệm công dân",
,"Tham gia vào xã hội thông qua việc sử dụng các dịch vụ số công cộng và tư nhân. Tìm kiếm được cơ hội, để trao quyền và thu hút công dân thông qua các công nghệ số phù hợp.",
2.3.CB2a,"a. Xác định được các dịch vụ số đơn giản để có thể tham gia vào xã hội.",
2.3.CB2b,"b. Nhận biết được các công nghệ số đơn giản, phù hợp để nâng cao năng lực cho bản thân và tham gia vào xã hội với tư cách là một công dân.",
NL thành phần 4,"2.4. Hợp tác thông qua công nghệ số",
,"Sử dụng được các công cụ và công nghệ số cho các quá trình hợp tác cũng như để cùng xây dựng và đồng sáng tạo dữ liệu, tài nguyên và kiến thức.",
2.4.CB2a,"a. Chọn được những công cụ và công nghệ số đơn giản cho các quá trình cộng tác.",
NL thành phần 5,"2.5. Quy tắc ứng xử trên mạng",
,"Nhận thức được các chuẩn mực hành vi và kiến thức khi sử dụng công nghệ số và tương tác trong môi trường số. Điều chỉnh các chiến lược giao tiếp phù hợp với đối tượng cụ thể và nhận thức đa dạng về văn hóa và thế hệ trong môi trường số.",
2.5.CB2a,"a. Phân biệt được các chuẩn mực hành vi đơn giản và bí quyết sử dụng công nghệ số và tương tác trong môi trường số.",
2.5.CB2b,"b. Chọn được các phương thức và chiến lược giao tiếp đơn giản phù hợp trong môi trường sổ.",
2.5.CB2c,"c. Phân biệt các khía cạnh đơn giản của sự đa dạng về văn hóa và thế hệ cần được tính đến trong môi trường số.",
NL thành phần 6,"2.6. Quản lý danh tính số",
,"Tạo và quản lý được một hoặc nhiều danh tính số để bảo vệ danh tiếng của bản thân, làm việc với dữ liệu mà một người tạo ra bằng nhiều công cụ môi trường và dịch vụ số.",
2.6.CB2a,"a. Xác định được danh tính số.",
2.6.CB2b,"b. Mô tả được những cách đơn giản để bảo vệ danh tiếng trực tuyến của bản thân.",
2.6.CB2c,"c. Nhận biết được dữ liệu đơn giản do mình tạo ra thông qua các công cụ, môi trường hoặc dịch vụ số.",
Miền NL 3,3. Sáng tạo nội dung số,Tin học
NL thành phần 1,"3.1 Phát triển nội dung số",
,"Tạo và chỉnh sửa được nội dung số ở các định dạng khác nhau, nhằm thể hiện bản thân thông qua các phương tiện số.",
3.1.CB2a,"a. Xác định được các cách tạo và chỉnh sửa nội dung đơn giản ở các định dạng đơn giản,",
3.1.CB2b,"b. Chọn được cách thể hiện bản thân thông qua việc tạo ra các nội dung số đơn giản.",
NL thành phần 2,"3.2. Tích hợp và tạo lập lại nội dung số",
,"Sửa đổi, tinh chỉnh và tích hợp được thông tin và nội dung mới vào khối kiến thức và tài nguyên hiện có để tạo ra nội dung và kiến thức mới, độc đáo và phù hợp.",
3.2.CB2a,"a. Chọn được các cách sửa đổi, tinh chỉnh, cải thiện và tích hợp các mục đơn giản có nội dung và thông tin mới để tạo ra những nội dung và thông tin mới và độc đáo.",
NL thành phần 3,"3.3. Thực thi bản quyền và giấy phép",
,"Hiểu được cách áp dụng bản quyền và giấy phép cho thông tin và nội dung số",
3.3.CB2a,"a. Xác định được các quy tắc đơn giản về bản quyền và giấy phép áp dụng cho dữ liệu, thông tin và nội dung số.",
NL thành phần 4,3.4 Lập trình,
,"Lập được kế hoạch và phát triển được một chuỗi các câu lệnh dễ hiểu cho một hệ thống máy tính để giải quyết một vấn đề nhất định hoặc thực hiện một nhiệm vụ cụ thể",
3.4.CB2a,"a. Liệt kê được các hướng dẫn đơn giản để hệ thống máy tính giải quyết một vấn đề đơn giản hoặc thực hiện một nhiệm vụ đơn giản.",
Miền NL 4,4. An toàn,Tin học
NL thành phần 1,"4.1. Bảo vệ thiết bị",
,"Bảo vệ được thiết bị và nội dung số; hiểu được rõ rủi ro và mối đe dọa trong môi trường số; nắm được các biện pháp an toàn và bảo mật; quan tâm đến mức độ tin cậy và quyền riêng tư.",
4.1.CB2a,"a. Nhận biết được cách bảo vệ thiết bị và nội dung số một cách đơn giản.",
4.1.CB2b,"b. Phân biệt được rủi ro và mối đe dọa đơn giản trong môi trường số.",
4.1.CB2c,"c. Tuân theo được các biện pháp an toàn và bảo mật đơn giản.",
4.1.CB2d,"d. Nhận biết được những cách thức đơn giản để quan tâm đến mức độ tin cậy và quyền riêng tư.",
NL thành phần 2,"4.2 Bảo vệ dữ liệu cá nhân và quyền riêng tư",
,"Bảo vệ được dữ liệu cá nhân và quyền riêng tư trong môi trường số. Hiểu được cách sử dụng và chia sẻ thông tin định danh cá nhân một cách an toàn có khả năng bảo vệ bản thân và người khác. Hiểu được cách các dịch vụ số sử dụng “Chính sách Quyền riêng tư” để thông báo phương thức sử dụng dữ liệu cá nhân.",
4.2.CB2a,"a. Lựa chọn được những cách thức đơn giản để bảo vệ dữ liệu cá nhân và quyền riêng tư trong môi trường số.",
4.2.CB2b,"b. Nhận biết được các cách sử dụng và chia sẻ thông tin định danh cá nhân một cách an toàn, có khả năng bảo vệ bản thân và người khác.",
4.2.CB2c,"c. Nhận diện được các tuyên bố cơ bản trong chính sách quyền riêng tư về cách sử dụng dữ liệu cá nhân trong dịch vụ số.",
NL thành phần 3,"4.3 Bảo vệ sức khỏe và an sinh số",
,"Tránh được rủi ro và đe dọa đến sức khỏe thể chất và tinh thần khi sử dụng công nghệ số. Bảo vệ được bản thân và người khác khỏi nguy cơ trong môi trường số (ví dụ: bắt nạt trên mạng). Nhận biết được những công nghệ số cho tăng cường thịnh vượng xã hội và sự hòa hợp trong xã hội.",
4.3.CB2a,"a. Phân biệt được các cách thức đơn giản để tránh rủi ro và đe dọa đến sức khỏe thể chất và tinh thần khi sử dụng công nghệ số.",
4.3.CB2b,"b. Lựa chọn được những cách thức đơn giản để bảo vệ bản thân khỏi nguy cơ trong môi trường số.",
4.3.CB2c,"c. Nhận biết được những công nghệ số đơn giản cho tăng cường thịnh vượng xã hội và sự hòa hợp trong xã hội.",
NL thành phần 4,"4.4 Bảo vệ môi trường",
,"Nhận thức được tác động của công nghệ số và việc sử dụng công nghệ số đối với môi trường.",
4.4.CB2a,"a. Nhận biết được tác động cơ bản của công nghệ số và việc sử dụng công nghệ số đối với môi trường.",
Miền NL 5,5. Giải quyết vấn đề,Tin học
NL thành phần 1,"5.1. Giải quyết các vấn đề kỹ thuật",
,"Xác định được các vấn đề kỹ thuật khi vận hành thiết bị, sử dụng môi trường số và giải quyết chúng (từ xử lý sự cố đến giải quyết các vấn đề phức tạp hơn).",
5.1.CB2a,"a. Xác định được các vấn đề kỹ thuật đơn giản khi vận hành thiết bị và sử dụng môi trường số.",
5.1.CB2b,"b. Xác định được các giải pháp đơn giản để giải quyết chúng.",
NL thành phần 2,"5.2 Xác định nhu cầu và giải pháp công nghệ",
,"Đánh giá được nhu cầu và xác định, đánh giá, lựa chọn, sử dụng các công cụ số cùng với các giải pháp công nghệ khả thi để giải quyết chúng. Điều chỉnh và tùy chỉnh được môi trường số theo nhu cầu cá nhân (ví dụ: khả năng tiếp cận).",
5.2.CB2a,"a. Xác định được nhu cầu cá nhân.",
5.2.CB2b,"b. Nhận ra được các công cụ số đơn giản và các giải pháp công nghệ có thể có để giải quyết những nhu cầu đó.",
5.2.CB2c,"c. Chọn được những cách đơn giản để điều chỉnh và tùy chỉnh môi trường số theo nhu cầu cá nhân.",
NL thành phần 3,"5.3 Sử dụng sáng tạo công nghệ số",
,"Sử dụng các công cụ và công nghệ số để tạo ra kiến thức, đổi mới quy trình và sản phẩm. Gắn kết cá nhân và tập thể vào quá trình xử lý nhận thức để hiểu và giải quyết các vấn đề mang tính khái niệm và các tình huống có vấn đề trong môi trường số.",
5.3.CB2a,"a. Xác định được các công cụ và công nghệ số đơn giản có thể được sử dụng để tạo ra kiến thức và đổi mới quy trình cũng như sản phẩm.",
5.3.CB2b,"b. Tuân theo quy trình nhận thức đơn giản của cá nhân và tập thể để hiểu và giải quyết các vấn đề khái niệm đơn giản và các tình huống có vấn đề trong môi trường số.",
NL thành phần 4,"5.4 Xác định các vấn đề cần cải thiện về NLS",
,"Hiểu được NLS của chính mình cần được cải thiện hoặc cập nhật ở đâu. Có thể hỗ trợ người khác phát triển NLS của họ. Tìm kiếm được cơ hội phát triển bản thân và cập nhật sự phát triển số.",
5.4.CB2a,a. Nhận ra được NLS của tôi cần được cải thiện hoặc cập nhật ở đâu.,
5.4.CB2b,b. Xác định được nơi để tìm kiếm cơ hội phát triển bản thân và cập nhật sự phát triển công nghệ số.,
Miền NL 6,6. Ứng dụng trí tuệ nhân tạo,
NL thành phần 1,6.1 Hiểu biết về trí tuệ nhân tạo,
,"Sử dụng hiệu quả các hệ thống AI và hiểu rõ ứng dụng thực tế của chúng. Sử dụng được AI để tạo nội dung, khám phá kiến thức và giải quyết các vấn đề trong công việc và cuộc sống hàng ngày.",
6.1.CB2a,a. Xác định được các khái niệm cơ bản của AI.,
6.1.CB2b,b. Nhớ lại được các ứng dụng đơn giản của AI trong cuộc sống hàng ngày.,
NL thành phần 2,6.2 Sử dụng trí tuệ nhân tạo,
,"Đánh giá và lọc được thông tin từ các nguồn được tạo ra hoặc xử lý bằng AI, để hiểu rõ hơn về tính đáng tin cậy và cách sử dụng thông tin đó. Đánh giá được AI trên các khía cạnh minh bạch, an toàn, đạo đức và tác động.",
6.2.CB2a,a. Áp dụng được các công cụ AI để giải quyết vấn đề đơn giản.,
6.2.CB2b,b. Tương tác được với các hệ thống AI cơ bản.,
6.2.CB2c,c. Tuân thủ các quy định pháp luật cơ bản khi sử dụng AI.,
NL thành phần 3,6.3 Đánh giá trí tuệ nhân tạo,
,"Đánh giá và lọc được thông tin từ các nguồn được tạo ra hoặc xử lý bằng AI, để hiểu rõ hơn về tính đáng tin cậy và cách sử dụng thông tin đó. Đánh giá được AI trên các khía cạnh minh bạch, an toàn, đạo đức và tác động.",
6.3.CB2a,"a. Nhận diện được các yếu tố cơ bản của hệ thống AI cần được đánh giá.",
6.3.CB2b,"b. Mô tả được các chức năng chính của hệ thống AI.",
`;
